print("Operator Precedence")
print("Operator \t Description")
print("** \t Exponent")
print("+x, –x, ~x \t Positive, negative, bitwise NOT")
print("*, /, //, %	Multiplication, division, remainder")
print("+, –	\t Addition, subtraction")
print("<<, >> \t Bitwise left and right shifts")
print("& \t Bitwise AND")
print("^ \t Bitwise XOR")
print("| \t Bitwise OR")
print("in, not in, is, is not, <, >,<=, >=,!=, ==, <> \t Comparisons, identity, and membership operators")
print("not \t Boolean NOT")
print("and \t Boolean AND")
print("or \t Boolean OR")
print("if- else \t Conditional expression")